# Generated by Django 4.0.3 on 2022-04-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('compid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('jobid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('jobdomain', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('minsalary', models.IntegerField()),
                ('maxsalary', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
