# Generated by Django 4.0.3 on 2022-04-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('testid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('instructions', models.CharField(max_length=1000)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('qid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.test')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('oid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('correct', models.BooleanField(default=False)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.question')),
            ],
        ),
    ]
