# Generated by Django 4.0.4 on 2022-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_comp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='jsonData',
            field=models.JSONField(blank=True, default='', null=True),
        ),
    ]
