# Generated by Django 4.0.3 on 2022-04-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_test_question_option'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=False)),
                ('cv', models.FileField(upload_to='uploads/')),
                ('linkedin', models.CharField(max_length=100)),
                ('pending', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.test')),
            ],
        ),
    ]
