# Generated by Django 4.0.4 on 2022-05-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_test_jsondata'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response1',
            name='compid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
