# Generated by Django 4.0.4 on 2022-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_response1_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cand_password',
            field=models.CharField(max_length=255),
        ),
    ]
