# Generated by Django 4.0.4 on 2022-05-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_response1_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response1',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
