# Generated by Django 4.0.4 on 2022-04-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_cand_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='response1',
            name='suggested_role',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
