# Generated by Django 4.0.4 on 2022-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_response1_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='response1',
            name='suggested_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='cand_personality',
            field=models.CharField(max_length=100),
        ),
    ]
