# Generated by Django 4.0.4 on 2022-05-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_response1_suggested_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response1',
            name='cand_personality',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
