# Generated by Django 4.0.4 on 2022-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_response1_cand_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response1',
            name='cand_personality',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='response1',
            name='suggested_role',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
