# Generated by Django 4.0.4 on 2022-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_response1_cand_personality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response1',
            name='topfive_personality',
            field=models.TextField(null=True),
        ),
    ]
