# Generated by Django 4.0.4 on 2022-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response1',
            name='cv',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
