# Generated by Django 4.0.4 on 2022-05-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_response1_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response1',
            name='cv',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
