# Generated by Django 4.0.4 on 2022-04-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('compid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=1000)),
                ('comp_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('jobdomain', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('minsalary', models.IntegerField()),
                ('maxsalary', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=1000)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.job')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.test')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('correct', models.BooleanField(default=False)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.question')),
            ],
        ),
    ]
