export { default as Navbar } from './navbar/Navbar';
export {default as JobCard} from "./jobcard/JobCard";
export {default as AptitudeTest} from "./AptitudeTest";
export {default as Records} from "./Records";
export {default as Confirmation} from "./confirmation";
export {default as Register} from "./Register";
export {default as FindCandidates} from "./findCandidates";
export {default as Login} from "./Login";
export {default as CreateTest} from "./CreateTest";
export {default as PerformanceDash} from "./PerformanceDash";
export {default as ViewApplications} from "./viewApplications";
export {default as Timer} from "./Timer";